### ISSUE TITLE
Supervisor Meeting - September 24th, 2024

### ISSUE THREAD

**Issue by gr812b** [gr812b/CVT-Simulator#17]
September 24th, 2024 at 11:30AM

**Attendance**

- [X] Kai Arseneau
- [X] Travis Wing
- [X] Cameron Dunn
- [X] Grace McKenna

**Agenda**
- Discuss meeting schedule
- Understanding Dr. Smith's role as a stakeholder
- Preferred method of review / feedback
- Questions about extras
- Extra discussion on deliverable 1

**Questions to Ask**

-

**Comment by gr4cem** [comment]
[September 24th Supervisor Meeting.pdf](https://github.com/user-attachments/files/17119267/September.24th.Supervisor.Meeting.pdf)

**Comment by smiths** [comment]
Nice summary notes!

I mentioned during the meeting that I would send you example SRS documents.  Here are some examples:

- [Drasil generated examples](https://jacquescarette.github.io/Drasil/), scroll down to Generated Examples and click on the SRS links (there are html, pdf and mdbook versions)
- [Game physics example, includes F =ma](https://jacquescarette.github.io/Drasil/examples/gamephysics/SRS/HTML/GamePhysics_SRS.html) (There is also a LaTeX version.)
- [The slope stability analysis program](https://jacquescarette.github.io/Drasil/examples/ssp/SRS/HTML/SSP_SRS.html#Sec:TMs) also has F = ma
- [A damped harmonic oscillator](https://github.com/WaqarAwan376/Damped_Harmonic_Oscillator-CAS741)
- [Inverted pendulum control system](https://github.com/mirzaim/IPCS/blob/main/docs/SRS/SRS.pdf)

**Comment by smiths** [comment]
The meeting is over, so you should probably close the issue.  :smile:
