### ISSUE TITLE
Team Meeting - September 23rd, 2024

### ISSUE THREAD

**Issue by t-wing11** [gr812b/CVT-Simulator#19]
**September 23rd, 2024**

**Attendance**

- [x] Kai Arseneau
- [x] Travis Wing
- [x] Cameron Dunn
- [x] Grace McKenna

**Agenda**
- Review Problem statement and Development Plan documents 
- Address To Do's for Deliverable 1 that are still left

**Comment by gr4cem** [comment]
[Sept23rd_meeting_notes.docx](https://github.com/user-attachments/files/17106103/Sept23rd_meeting_notes.docx)
