### ISSUE TITLE
TA Meeting - October 7th, 2024

### ISSUE THREAD

**Issue by t-wing11** [gr812b/CVT-Simulator#32]
**SRS Review**

**October 7th, 2024**

**Attendance**

- [ ] Kai Arseneau
- [ ] Travis Wing
- [ ] Cameron Dunn
- [ ] Grace McKenna

**Questions to Ask**
- Theoretical Models 
- Instance Models
- What is a data definition
- Questions about traceability matrices

**Comment by gr4cem** [comment]
[Oct 7th TA Meeting .pdf](https://github.com/user-attachments/files/17284133/Oct.7th.TA.Meeting.pdf)
