### ISSUE TITLE
TA Meeting - October 28th, 2024

### ISSUE THREAD

**Issue by camdnnn** [gr812b/CVT-Simulator#56]
VnV Plan

October 28th, 2024 at 3:15 pm

**Attendance**

- [x] Kai Arseneau
- [x] Travis Wing
- [x] Cameron Dunn
- [x] Grace McKenna

**Questions to Ask**

-

**Comment by gr4cem** [comment]
[Vnv Meeting.pdf](https://github.com/user-attachments/files/17563512/Vnv.Meeting.pdf)
